USE INFORMATION;
CREATE TABLE STUDENT
(
ID INTEGER PRIMARY KEY,
NAME VARCHAR (20),
DEPARTMENT VARCHAR (20)
);
SHOW TABLES;
SELECT * FROM STUDENT;
INSERT INTO STUDENT VALUES (1, 'ASHWINI' , 'IT');
INSERT INTO STUDENT (ID, DEPARTMENT, NAME) VALUES (2, 'SHUBHAM' , 'IT');
INSERT INTO STUDENT (ID, DEPARTMENT, NAME) VALUES (3, 'KARTIK' , 'IT');
ALTER TABLE STUDENT ADD JOIN_ DATE;
ALTER TABLE STUDENT MODIFY NAME VARCHAR (100);
ALTER TABLE STUDENT RENAME TO STUD;
ALTER TABLE STUD RENAME TO STUDENT;
ALTER TABLE STUDENT DROP COLUMN JOIN_DATE;
TRUNCATE TABLE STUDENT;
DROP TABLE STUDENT;














