USE INFO;
CREATE TABLE EMPLOYEE
(
EID INTEGER PRIMARY KEY,
ENAME VARCHAR(20),
EDEPARTMENT VARCHAR(20),
ESALARY INTEGER,
DEPNO INTEGER
);
SELECT*FROM EMPLOYEE;
INSERT INTO EMPLOYEE VALUES(1, 'ASHWINI', 'IT', 50000,10);
INSERT INTO EMPLOYEE VALUES(2, 'SHUBHAM', 'IT', 80000,10);
INSERT INTO EMPLOYEE VALUES(3, 'ANIKET', 'IT', 70000,10);

SELECT (ESALARY+300)*12 AS "ANNUAL SALARY WITH BONUS" FROM EMPLOYEE;
INSERT INTO EMPLOYEE VALUES(4, 'PARTH', 'OPERATION',50000,20);
INSERT INTO EMPLOYEE VALUES(5, 'VIKAS', 'OPERATION',80000,20);
INSERT INTO EMPLOYEE VALUES(6, 'ANSHU', 'OPERATION',70000,20);
SELECT DISTINCT ESALARY FROM EMPLOYEE;
SELECT * FROM EMPLOYEE WHERE ENAME='SHUBHAM';
SELECT * FROM EMPLOYEE WHERE EDEPARTMENT='IT';
SELECT* FROM EMPLOYEE WHERE EID=4;
SELECT* FROM EMPLOYEE WHERE ESALARY>60000;
SELECT* FROM EMPLOYEE WHERE ESALARY<60000;
SELECT* FROM EMPLOYEE WHERE ESALARY>=50000;
SELECT* FROM EMPLOYEE WHERE ESALARY<=50000;
SELECT* FROM EMPLOYEE WHERE ESALARY BETWEEN 60000 AND 80000;
SELECT* FROM EMPLOYEE WHERE EID BETWEEN 1 AND 5;
INSERT INTO EMPLOYEE VALUES (7, 'MADHURI', 'COMPUTER', 60000,30);
INSERT INTO EMPLOYEE VALUES (8, 'GAURAV', 'COMPUTER', 60000,30);
INSERT INTO EMPLOYEE VALUES (9, 'ALISHA', 'COMPUTER', 90000,30);
SELECT * FROM EMPLOYEE WHERE EDEPARTMENT IN('IT', 'COMUTER');
SELECT * FROM EMPLOYEE WHERE EID IN (1,3,5,7);
SELECT * FROM EMPLOYEE WHERE ENAME LIKE 'A%';
SELECT * FROM EMPLOYEE WHERE ENAME LIKE 'AN%';
SELECT * FROM EMPLOYEE WHERE ENAME LIKE '%I';
SELECT * FROM EMPLOYEE WHERE ENAME LIKE '%R_';

CREATE TABLE A
(
ID INTEGER,
COMPLETED BOOLEAN
);
SHOW TABLES;
INSERT INTO A VALUES(1,TRUE);
INSERT INTO A VALUES(2,FALSE);
INSERT INTO A VALUES(3,TRUE);
INSERT INTO A VALUES(4,FALSE);
INSERT INTO A VALUES(5,TRUE);
SELECT*FROM A;
SELECT*FROM A WHERE COMPLETED IS TRUE;
SELECT*FROM A WHERE COMPLETED IS FALSE;

USE INFO;
SHOW TABLES;
CREATE TABLE CUSTOMER1
(
CID INTEGER,
CNAME VARCHAR(40),
AREA VARCHAR(40),
PIN INTEGER,
CONTACT INTEGER
);

SELECT*FROM CUSTOMER1;
INSERT INTO CUSTOMER1 VALUE(10, 'SHUBHAM', 'KOTHRUD', 411038, 12346790);
INSERT INTO CUSTOMER1 VALUE(20, 'VIKAS', 'BAVDHAN', 411008, 0123456789);
INSERT INTO CUSTOMER1 VALUE(30, 'ANIKET', 'BANER', 411045, 123467760);

CREATE TABLE ORDER1
(
OID INTEGER,
CID INTEGER,
SID INTEGER,
EID INTEGER,
PRICE INTEGER
);
SELECT* FROM ORDER1;
INSERT INTO ORDER1 VALUES(11,10,111,1,50);
INSERT INTO ORDER1 VALUES(12,20,222,2,100);
INSERT INTO ORDER1 VALUES(13,30,333,3,150);
SELECT OID, PRICE,CNAME
FROM ORDER1
INNER JOIN CUSTOMER1
ON CUSTOMER1.CID=ORDER1.CID;

CREATE TABLE SHIPPER1
(
SID INTEGER,
SHANME VARCHAR(40),
PHONE INTEGER
);
INSERT INTO SHIPPER1 VALUE(111, 'BLINKET', 123454321);
INSERT INTO SHIPPER1 VALUE(222, 'ZOMATO', 1234123412);
INSERT INTO SHIPPER1 VALUE(333, 'BIGBASKET', 1231231231);
SELECT* FROM SHIPPER1;

SELECT CUSTOMER1.CNAME,ORDER1.OID
FROM CUSTOMER1
LEFT JOIN ORDER1
ON CUSTOMER1.CID=ORDER1.CID;

CREATE TABLE EMPLOYEE1
(
EID INTEGER,
ENAME VARCHAR(40),
DEPNO INTEGER
);
INSERT INTO EMPLOYEE1 VALUE(1,'KARTIK', 10);
INSERT INTO EMPLOYEE1 VALUE(2,'PARTH', 20);
INSERT INTO EMPLOYEE1 VALUE(3,'ANSHU', 30);
SELECT*FROM EMPLOYEE1;
 SELECT ORDER1.OID, EMPLOYEE1.ENAME,
 EMPLOYEE1.DEPNO
 FROM ORDER1
 RIGHT JOIN EMPLOYEE1
 ON ORDER1.EID=EMPLOYEE1.EID;
 
  SELECT EMPLOYEE1.ENAME, ORDER1.OID
  FROM EMPLOYEE1
 LEFT JOIN ORDER1
 ON EMPLOYEE1.EID=ORDER1.EID;

SELECT ORDER1.OID , CUSTOMER1.CNAME,
CUSTOMER1.AREA
FROM ORDER1
RIGHT JOIN CUSTOMER1
ON ORDER1.CID=CUSTOMER1.CID;
 
 













