USE INFO;
CREATE TABLE EMPLOYEE
(
EID INTEGER PRIMARY KEY,
ENAME VARCHAR(20),
EDEPARTMENT VARCHAR(20),
ESALARY INTEGER,
DEPNO INTEGER
);
SELECT*FROM EMPLOYEE;
INSERT INTO EMPLOYEE VALUES(1, 'ASHWINI', 'IT', 50000,10);
INSERT INTO EMPLOYEE VALUES(2, 'SHUBHAM', 'IT', 80000,10);
INSERT INTO EMPLOYEE VALUES(3, 'ANIKET', 'IT', 70000,10);
SELECT ESALARY+300 AS "NEW_SAL" ,ESALARY FROM EMPLOYEE;
SELECT (ESALARY+300)*12 AS "ANNUAL SALARY WITH BONUS" FROM EMPLOYEE;
INSERT INTO EMPLOYEE VALUES(4, 'PARTH', 'OPERATION',50000,20);
INSERT INTO EMPLOYEE VALUES(5, 'VIKAS', 'OPERATION',80000,20);
INSERT INTO EMPLOYEE VALUES(6, 'ANSHU', 'OPERATION',70000,20);
SELECT DISTINCT ESALARY FROM EMPLOYEE;
SELECT * FROM EMPLOYEE WHERE ENAME='SHUBHAM';
SELECT * FROM EMPLOYEE WHERE EDEPARTMENT='IT';
SELECT* FROM EMPLOYEE WHERE EID=4;
SELECT* FROM EMPLOYEE WHERE ESALARY>60000;
SELECT* FROM EMPLOYEE WHERE ESALARY<60000;
SELECT* FROM EMPLOYEE WHERE ESALARY>=50000;
SELECT* FROM EMPLOYEE WHERE ESALARY<=50000;
SELECT* FROM EMPLOYEE WHERE ESALARY BETWEEN 60000 AND 80000;
SELECT* FROM EMPLOYEE WHERE EID BETWEEN 1 AND 5;
INSERT INTO EMPLOYEE VALUES (7, 'MADHURI', 'COMPUTER', 60000,30);
INSERT INTO EMPLOYEE VALUES (8, 'GAURAV', 'COMPUTER', 60000,30);
INSERT INTO EMPLOYEE VALUES (9, 'ALISHA', 'COMPUTER', 90000,30);
SELECT * FROM EMPLOYEE WHERE EDEPARTMENT IN('IT', 'COMUTER');
SELECT * FROM EMPLOYEE WHERE EID IN (1,3,5,7);
SELECT * FROM EMPLOYEE WHERE ENAME LIKE 'A%';
SELECT * FROM EMPLOYEE WHERE ENAME LIKE 'AN%';
SELECT * FROM EMPLOYEE WHERE ENAME LIKE '%I';
SELECT * FROM EMPLOYEE WHERE ENAME LIKE '%R_';




