USE INFORMATION;
CREATE TABLE EMPLOYEE
(
EID INTEGER PRIMARY KEY,
ENAME VARCHAR(30),
EDEPARTMENT VARCHAR(30),
ESALARY INTEGER
);
SHOW TABLES;
SELECT*FROM EMPLOYEE;
INSERT INTO EMPLOYEE VALUES(1,'SHUBHAM','IT',50000); 
INSERT INTO EMPLOYEE VALUES(2,'ASHWINI','IT',60000); 
INSERT INTO EMPLOYEE VALUES(3,'ANIKET','IT',70000); 
INSERT INTO EMPLOYEE VALUES(4,'PARTH','IT',50000); 
INSERT INTO EMPLOYEE VALUES(5,'VIKAS','IT',60000); 
INSERT INTO EMPLOYEE VALUES(6,'ANSHU','IT',70000); 
INSERT INTO EMPLOYEE VALUES(7,'MADHURI','COMPUTER',70000); 
SELECT DISTINCT ESALARY FROM EMPLOYEE;
SELECT * FROM EMPLOYEE WHERE ENAME='SHUBHAM';
SELECT * FROM EMPLOYEE WHERE EDEPARTMENT='COMPUTER';
SELECT * FROM EMPLOYEE WHERE EDEPARTMENT='IT';


